### ISSUE TITLE
Bug: Cannot Clone Repository

### ISSUE THREAD

**Issue by taigrr** [PythonNut/su.el#1]
#### Issue description

Unfortunately, when I try to clone this repository, git warns that it is empty.
Dev apparently forgot to upload the code!

#### Steps to reproduce the issue

1.   git clone git@github.com:PythonNut/su.el.git

#### What's the expected result?

- The code for this repository should be available through a git clone

#### What's the actual result?

- There is no code in the repo

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/8261498/44122280-fe855010-9fd7-11e8-8e55-4a1f232b5c48.png)

**Comment by PythonNut** [comment]
Joke's on you. There is no code. :P

**Comment by taigrr** [comment]
![image](https://user-images.githubusercontent.com/8261498/44135430-e82df4ca-a01d-11e8-92aa-6bed6aef0741.png)

**Comment by PythonNut** [comment]
Initial code has been pushed. Note: Code is likely not in a working state and is not publishable.
