### ISSUE TITLE
Comparison with similar packages

### ISSUE THREAD

**Issue by QiangF** [PythonNut/su.el#10]
Auto-sudoedit looks similar:
https://github.com/ncaq/auto-sudoedit

**Comment by PythonNut** [comment]
There are several "sudo" packages, so let me address them all at once. I will compare with [sudo-edit](https://github.com/nflath/sudo-edit) and [auto-sudoedit](https://github.com/ncaq/auto-sudoedit). I don't believe that [sudo-ext](https://github.com/rubikitch/sudo-ext) is comparable to `su.el` as it does not use TRAMP.

I believe `su.el` has several advantages over existing packages:

1. Robust TRAMP path calculation. `su.el` works even if you are already using TRAMP (e.g. for editing a remote file). 

    This adds substantial complexity. As of now, I believe `auto-sudoedit` does not support this at all. `sudo-edit` does support this as long as the first hop is done using the `ssh` method. `su.el` will automatically calculate the corresponding inline method to use for the first hop (so it is not limited to `ssh`). In fact, it may even work for some _custom_ TRAMP methods. Additionally, I believe the solution in `su.el` is slightly more robust since it uses TRAMP's own file name parser to transform the file name.

2. Supports both `su` and `sudo`. 

    I believe neither `sudo-edit` not `auto-sudoedit` support using `su` for privilege escalation. Additionally, `su.el` can automatically detect which one to use. `su.el` also detects whether `sudo` requires a password and will prompt for confirmation if it does not, in order to prevent you from writing accidentally. 

3. `su.el` requires the minimum amount of user interaction.

    If you are using `su` or require a password for `sudo`, `auto-sudoedit` will prompt you for credentials whenever you open a file you can't write. On the other hand, `su.el` prompts only when you attempt to write modifications to the file. You will save time with `su.el` if you view a file but do not edit it.

    If you are using `sudo-edit`, you will need to manually indicate that you wish to open the file with `sudo` before you perform any writes, either by opening the file using `sudo-edit-find-file` or by using `sudo-edit` after the file has been opened. On the other hand, `su.el` will automatically perform the privilege escalation on write.

There are potentially other ancillary features provided by `auto-sudoedit` or `sudo-edit` but not `su.el`. Right now, I am focused on the core privilege escalation mechanics. If there is some feature that `su.el` is missing, I would be happy to consider adding it.

This is why I believe `su.el` is sufficiently innovative. It is not perfect, and I hope that any potential wrinkles left in it will be ironed out in the future. I am interested in any feedback you may have on this topic.
