### ISSUE TITLE
Disable `view-mode' if needed.

### ISSUE THREAD

**Issue by overideal** [PythonNut/su.el#14]
When the variable _view-read-only_ is non-nil, _view-mode_ is automatically enabled when a file is visited read-only.
Currently, this package removes read-only from the desired buffers, but it does not disable _view-mode_.
Therefore, when using this package and visiting a root-owned file, the file becomes writable, but read-only mode stays on, which of course should not happen.
The fix is simple, in `su--edit-file-as-root-maybe`, add the expression
```
(when view-mode
        (view-mode -1))
```
above `(setq buffer-read-only nil)`.

**Comment by PythonNut** [comment]
I don't use `view-mode` but this seems reasonable to me.
