### ISSUE TITLE
Add to MELPA

### ISSUE THREAD

**Issue by PythonNut** [PythonNut/su.el#2]
- [ ] Finish arbitrary user generalization
- [x] Add `README.md`
- [x] Add Commentary
- [x] Add autoloads
- [ ] Test

**Comment by raxod502** [comment]
- [x] Add MIT License

**Comment by PythonNut** [comment]
See https://github.com/melpa/melpa/pull/7048

**Comment by raxod502** [comment]
Last I checked, MELPA's usual policy for notoriety is a minimum of 50 stars. However, we shall see what happens.

**Comment by manuel-uberti** [comment]
FWIW, I left a comment noting the package works as expected. :)
