### ISSUE TITLE
Change owner when editing a file

### ISSUE THREAD

**Issue by arkhan** [PythonNut/su.el#8]
Greetings, great work with this package.

I noticed this inconvenience when editing a /etc/sudoers file

When modifying this change owner from root:root to arkhan:arkhan which started making noise when using the sudo command.

This can be prevented.

Thank you

**Comment by PythonNut** [comment]
That's interesting, I cannot reproduce this on my own system. Can you provide more details regarding how this came about?

**Comment by arkhan** [comment]
apparently the problem is in my configuration, sorry for the false alarm
